### ISSUE TITLE
Usage of preemptible machines

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/workshop2022-lesson-introcloud#1]
@alextintin007, it would be good to add the option of using [preemptible machines](https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms) to reduce costs in the appropriate place as a side note or something.

**Comment by xaviertintin** [comment]
This has been added to:
3. [Demo: Creating a cluster](https://cms-opendata-workshop.github.io/workshop2022-lesson-introcloud/03-demo1/index.html)
