### ISSUE TITLE
Take out requirement of having checked previous material

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/workshop2022-lesson-introcloud#2]
@Khajauli @alextintin007 I don't think we should make a [hard requirement](https://github.com/cms-opendata-workshop/workshop2022-lesson-introcloud/blob/gh-pages/index.md#prerequisites) for people to have checked previous material.  The instructions in this pre-exercise should be mostly self contained.  You can make a reference to previous material, but note that it can be outdated also.

**Comment by xaviertintin** [comment]
I've added shell and docker as a prerequisite since it works with both. I've also noted it may be outdated but once the entire workshop is ready I'll update the new links.
