### ISSUE TITLE
04 - is the configmap patch needed?

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2022-lesson-introcloud#4]
In https://cms-opendata-workshop.github.io/workshop2022-lesson-introcloud/04-demo2/index.html
for the patch, I get 

```
~ (cms-opendata)$ kubectl patch configmap workflow-controller-configmap -n argo --patch "$(cat patch-workflow-controller-configmap.yaml)"
configmap/workflow-controller-configmap patched (no change)
```

From the message, it looks like there's no change. Is this still needed? Is it in the official `argo` instructions?

**Comment by xaviertintin** [comment]
It is not official but it was used in previous workshops, however I believe it is unnecessary so I've removed this
